### ISSUE TITLE
issues is with me the User 

### ISSUE THREAD

**Issue by ollyboustead** [ameyuuno/docker-unifi-led-light-switch#2]
HI
This is such a great idea but I am so green to how to use docker 
I am struggling to get it running 
is there a step by step (im sorry if the step by step guide) I have managed to pull to docker 
but I am unsure how to add all the information and get it to run.
Is there a idiots guide for people who have never used docker
Thanks for your time 
O

**Comment by ameyuuno** [comment]
Hi!
If you have problem with installation docker, I think you should start with this [page](https://docs.docker.com/get-docker/). There you will find installation instructions (for different OS).
After that just use [these commands](https://github.com/ameyuuno/docker-unifi-led-light-switch#using-docker) and, I hope, it will just work ^^

**Comment by ollyboustead** [comment]
Thanks - 
I m sorry I have docker installed 
do i just type as per the page ? in terminal with docker 
I type out all the text - the user name etc 
then I just stuck 
with > how to i end that editing ?

**Comment by ameyuuno** [comment]
To be honest, I don't understand what your problem is. Can you give more details (steps, screenshots, etc.)? Where did you stuck?

**Comment by ollyboustead** [comment]
Sorry I am not explaining well , 
Here is what I have done so far 
![Screenshot 2021-04-30 at 16 34 12](https://user-images.githubusercontent.com/74654022/116719064-8b495f80-a9d2-11eb-885d-59b1a97ae0d7.jpg)

**Comment by ameyuuno** [comment]
@ollyboustead I'm so sorry for that huge delay of answer.

Oh... It is my mistake - there should be `docker`'s subcommand `run` instead of `up`.
